### ISSUE TITLE
Lyndsey Project 1

### ISSUE THREAD

**Issue by LNewsome** [ga-dc/wdi8-project1-gallery#1]
Link to repo: https://github.com/LNewsome/project1/tree/gh-pages
Link to deployed app: http://lnewsome.github.io/project1/

Things you'd like specific feedback on:

**Comment by mattscilipoti** [comment]
:+1: Good job on Project 1!
I've completed your feedback.  Please review feedback_mms.md and the inline comments here:
https://github.com/mattscilipoti/wdi8-project1-ln/compare/gh-pages...feedback_mms
