### ISSUE TITLE
Patrick's Project 1 -- WAR

### ISSUE THREAD

**Issue by pkmoran** [ga-dc/wdi8-project1-gallery#11]
Link to repo: [Project 1 Repo](https://github.com/pkmoran/project-1.git)
Link to deployed app: [Project 1 Site](https://pkmoran.github.io/project-1)

Things you'd like specific feedback on:
- Code DRYness - how could I have cleaned things up a bit more?
- Possibility of additional features
- Card images take a long time to load, not sure how to resolve this.

**Comment by nolds9** [comment]
:+1: Please review feedback [here](https://github.com/pkmoran/project-1/pull/1)
