### ISSUE TITLE
Jeffrey Eaton's WAR

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-dc/wdi8-project1-gallery#12]
Link to repo: https://github.com/jeffreyeaton76/war
Link to deployed app: http://jeffreyeaton76.github.io/war/

Things you'd like specific feedback on: The three-player branch! I got pretty far with it; it runs normal play alright (only "declares war" on three-way ties) but starts to freak out when the first player goes out. This is because comparing is keyed off the length position of the cards in the array that holds the cards "in play" (stored in `war3.hand`). I introduced a "zero of hearts" concept and the first player to get one of those just has their pile reset to zero of hearts after every hand, but that crashes into the fact that war3.gameOver is only triggered when you run out of cards. I'm sorry you'll have to load it separately - it has a separate HTML/CSS/JS files and I didn't have time to properly merge them into a single toggling set.

**Comment by joe-gz** [comment]
Hi Jeff,

:+1: Great job on Project 1! I submitted a PR with inline comments and a feedback file to your repo and provided the links below

The link to the PR is here: https://github.com/jeffreyeaton76/war/pull/1/files
The link to the feedback file is here: https://github.com/joe-gz/war/blob/feedback/feedback_jgz.md

Please let me know if you have any more questions!
