### ISSUE TITLE
Mohamed's Project 1: Deadpool Trivia

### ISSUE THREAD

**Issue by mohamedrchalal** [ga-dc/wdi8-project1-gallery#13]
Link to repo: https://github.com/mohamedrchalal/DeadpoolTrivia
Link to deployed app:
http://mohamedrchalal.github.io/DeadpoolTrivia/
Things you'd like specific feedback on:
i'm pretty much good to go, did not have time to actually make the high score section, though i did get the localStorage to work!

**Comment by nolds9** [comment]
:+1: Please review feedback [here](https://github.com/mohamedrchalal/DeadpoolTrivia/pull/1)
