### ISSUE TITLE
Christine Movius Flash Cards (Language Translation)

### ISSUE THREAD

**Issue by christine-sm** [ga-dc/wdi8-project1-gallery#14]
Link to repo: https://github.com/cmmovius/flash-cards/tree/master
Link to deployed app: http://www.christinemovius.com/flash-cards/

Things I would like specific feedback on:
- For the quiz, I was having trouble making the cards show up one at a time. I could either make all of the cards show up at once using a for loop or isolate one card to show up without being able to later cycle through the cards. I would love to figure out how to tackle this.
- When I hover over the cards, they translate properly, but an error message shows up in the console. I understand why the error is happening, but I don't know how to fix it without messing up the translation.
- I would like to switch the hover mechanism to a click mechanism. However, I can't click back and forth between translations because they overwrite each other.

**Comment by beckybeauchamp1** [comment]
Hi Christine,

Great job on Project 1! I submitted a PR to your repo and included both the evaluation and inline comments. 

The link to the PR is here: https://github.com/cmmovius/flash-cards/pull/1/files
The link to the evaluation is here: https://github.com/beckybeauchamp1/flash-cards/blob/beckys-branch/evaluation-template.md

Please let me know if you have any more questions :+1:
