### ISSUE TITLE
Caitlin's Concentration Game

### ISSUE THREAD

**Issue by caitlindaitch** [ga-dc/wdi8-project1-gallery#15]
Link to repo: https://github.com/caitlindaitch/ConcentrationGame
Link to deployed app: http://caitlindaitch.github.io/ConcentrationGame/

Things you'd like specific feedback on: How to further clean up my code--I worked on refactoring it by putting it into an object and cleaning up some of the functions, but I would love any suggestions on how to improve it further. Also, any suggestions on how to improve the game would be great.

**Comment by beckybeauchamp1** [comment]
Hi Caitlin,

Awesome job on Project 1! Here is a link to the PR I have submitted to your repo with the evaluation and further inline comments: https://github.com/caitlindaitch/ConcentrationGame/pull/1/files

Please let me know if you have any further questions :+1:
