### ISSUE TITLE
Memory Grid

### ISSUE THREAD

**Issue by jblakeman** [ga-dc/wdi8-project1-gallery#17]
Link to repo: [github.com/jblakeman/memory-grid](https://github.com/jblakeman/memory-grid)
Link to deployed app: [memory-grid](https://jblakeman.github.io/memory-grid)

Things you'd like specific feedback on:

  Functionality, implementation
  Should I not have put it all in an object?  Keeping `this` in scope can be difficult when using methods in listeners that call other methods.

**Comment by joe-gz** [comment]
Hi John,

:+1: Great job on Project 1! I submitted a PR with inline comments and a feedback file to your repo and provided the links below

The link to the PR is here: https://github.com/jblakeman/memory-grid/pull/1/files
The link to the feedback file is here: https://github.com/joe-gz/memory-grid/blob/feedback/feedback_jgz.md

Please let me know if you have any more questions!
