### ISSUE TITLE
Matt's Memory Game

### ISSUE THREAD

**Issue by MattLeeStevens** [ga-dc/wdi8-project1-gallery#18]
Link to repo: https://github.com/MattLeeStevens/project1
Link to deployed app: http://mattleestevens.github.io/project1/

Things you'd like specific feedback on:  
I'm pretty happy with it.  This was a great learning experience.

**Comment by mattscilipoti** [comment]
:+1: Good job on Project 1!
I've completed your feedback.  Please review feedback_mms.md and the inline comments here: https://github.com/mattscilipoti/wdi8_project1_ms/compare/master...feedback_mms#diff-3d2307853d0fb6e1e0ee649b25ab2ea3R7
