### ISSUE TITLE
Melissa's Project1

### ISSUE THREAD

**Issue by holytoastr** [ga-dc/wdi8-project1-gallery#2]
Link to repo: https://github.com/holytoastr/project1
Link to deployed app: http://holytoastr.github.io/project1/

Things you'd like specific feedback on:
- When user clicks on multiple cards really fast, they get false matches. Do you have a suggestion on how to prevent that?
- The matchNumbers method loses its proper context when passed through setTimeout. Why?

**Comment by nolds9** [comment]
:+1:  Please see feedback [here](https://github.com/nolds9/mm_project1/pull/1/files) (Was unable to fork, so couldn't submit a PR for your repo)
