### ISSUE TITLE
Project 1 - Trivia Game

### ISSUE THREAD

**Issue by nyron** [ga-dc/wdi8-project1-gallery#20]
Link to repo: https://github.com/nyron/TriviaGame.git
Link to deployed app: http://nyron.github.io/TriviaGame/trivia.html

Things you'd like specific feedback on: How the game functions and additional features to be added. Note: the restart button does not work (it is in my triviagame.md file) but I will add that functionality this weekend. All in all it was great! can't wait for the next one.

**Comment by nolds9** [comment]
:+1:  Please see my feedback [here](https://github.com/nyron/TriviaGame/pull/1)
