### ISSUE TITLE
Keith Prifte's Project1: Memory Space

### ISSUE THREAD

**Issue by khenry10** [ga-dc/wdi8-project1-gallery#22]
Link to repo: https://github.com/khenry10/project1/tree/master
Link to deployed app: http://khenry10.github.io/project1/

Things you'd like specific feedback on: Best 'next' feature to add for js complexity/challenge.

**Comment by joe-gz** [comment]
Hi Keith,

:+1: Great job on Project 1! I submitted a PR with inline comments and a feedback file to your repo and provided the links below

The link to the PR is here: https://github.com/khenry10/project1/pull/1/files
The link to the feedback file is here: https://github.com/joe-gz/project1/blob/feedback/feedback_jgz.md

Please let me know if you have any more questions!
