### ISSUE TITLE
Brittany Branson's Week 3 Project

### ISSUE THREAD

**Issue by Dibbledl01** [ga-dc/wdi8-project1-gallery#23]
Link to repo: https://github.com/Dibbledl01/BrittanyBransonWeek3Project
Link to deployed app: https://github.com/Dibbledl01/BrittanyBransonWeek3Project.git

Things you'd like specific feedback on:

Unfortunately, my project isn't finished. But, I feel I've made HUGE progress even within the past 48 hours (in terms of execution as well as understanding of Javascript).

I know, right now, there is A LOT of code. I know there are plenty of ways of condensing what I've done into a lot less. But, breaking my code down the way I have has really helped me understand what is happening/being executed at each line. That being said, I would love feedback and options regarding how to condense it. That way, I can go back and compare.

Also, I've been a bit stuck on an if/else function to compare two cards that have been clicked. My card <divs> have quite a few classes and IDs attached to them at the moment, so I've been stuck with regards to what should I pull to compare in my function.

Thank you!

**Comment by beckybeauchamp1** [comment]
Hi Brittany,

Good job on Project 1! Here is a link to the PR I submitted to your repo with inline comments and evaluation template:

https://github.com/Dibbledl01/BrittanyBransonWeek3Project/pull/1/files

Please let me know if you have any questions :+1:
