### ISSUE TITLE
Ryan's Project

### ISSUE THREAD

**Issue by rkrolick** [ga-dc/wdi8-project1-gallery#24]
Link to repo: http://rkrolick.github.io/wdi_project1/
Link to deployed app: http://rkrolick.github.io/wdi_project1/

Things you'd like specific feedback on:
CSS on end screen does not seem to work.  Is this because the end screen's display is absolute?

Any ideas on how to better handle collision detection?

**Comment by nolds9** [comment]
:+1:  Please review feedback [here](https://github.com/rkrolick/wdi_project1/pull/1)
