### ISSUE TITLE
Cam Project1

### ISSUE THREAD

**Issue by CamLatimer** [ga-dc/wdi8-project1-gallery#26]
Link to repo: https://github.com/CamLatimer/WDI-Project-1-War
Link to deployed app: https://camlatimer.github.io/WDI-Project-1-War/

Things you'd like specific feedback on:
-Ideas on displaying cards / UI ideas
-how to DRY up code, keep things simple

**Comment by beckybeauchamp1** [comment]
Hi Cam,

Great job on Project 1! I have made a PR to your repo and included the evaluation template as well as inline comments. 

Here is the link to the PR: https://github.com/CamLatimer/WDI-Project-1-War/pull/1/files

Please let me know if you have any questions :+1:
