### ISSUE TITLE
Charles Hwang - Trivia Game

### ISSUE THREAD

**Issue by ghost** [ga-dc/wdi8-project1-gallery#27]
Link to repo: git@github.com:charlesthwang/project1.git
Link to deployed app: http://charlesthwang.github.io/project1/

Things you'd like specific feedback on:

For my gold version, I am working on changing the color of correct answer buttons to green and incorrect answer buttons to red. At the moment, the code for this feature is causing other methods to break. Stay tuned...

**Comment by beckybeauchamp1** [comment]
Hi Charles,

Great job on Project 1!! I submitted a PR to your repo with additional inline comments and the evaluation.md file. 

The link to the PR is here: https://github.com/charlesthwang/project1/pull/1/files

The evaluation template is here: https://github.com/beckybeauchamp1/project1/blob/beckys-branch/evaluation-template.md

Please let me know if you have any further questions :+1:
