### ISSUE TITLE
Kim's Project 1

### ISSUE THREAD

**Issue by kimcabb** [ga-dc/wdi8-project1-gallery#31]
Link to repo: https://github.com/kimcabb/project1
Link to deployed app: http://kimcabb.github.io/project1

Things you'd like specific feedback on:

All of it, please :)  

I ran into trouble last night with all my event handlers returning null.  I used searched Google and read that it could be attributed to the the DOM not loading quickly enough.  A StOv solution suggested I use a window.onload function.  It began working again but later affected other areas of my program, unfortunatelty.

I chose the trivia game because I could envision the logic from start to finish best out of all the choices, but I still struggled quite a bit with getting the pieces to work together. For example, prompting for the next question in successive order after the user submits their answers, showing/hiding the category div on the main page, etc.  This week presented its own personal challenges that limited my ability to dig as deep as I would have liked.  Overall, however, I really enjoyed this project, despite setbacks.  I learned a lot while working through it, and that speaks to more than just the code.  I look forward to working on it more in the coming weeks.

**Comment by mattscilipoti** [comment]
I've completed your feedback.  Please review feedback_mms.md and the inline comments here:
https://github.com/kimcabb/project1/pull/1/files
