### ISSUE TITLE
andrewSM_memory_game

### ISSUE THREAD

**Issue by arsm800** [ga-dc/wdi8-project1-gallery#32]
Link to repo: https://github.com/arsm800/project1
Link to deployed app: http://arsm800.github.io/project1/

Things you'd like specific feedback on:

How to keep the same numbers of tiles (div elements) on each row.  I think this might involve flexbox?

**Comment by amaseda** [comment]
You could use flexbox to accomplish this. You could also set the width of the tiles so that they always occupy a certain percentage of the width (i.e., set the width of each tile to ~10% so that 10 always appear in a given row -- you'll probably have to tweak this).
