### ISSUE TITLE
Matt K's Solution (Project War)

### ISSUE THREAD

**Issue by mkernsNCR** [ga-dc/wdi8-project1-gallery#33]
Link to repo: https://github.com/mkernsNCR/project-war/tree/master
Link to deployed app: http://mkernsncr.github.io/project-war

Things you'd like specific feedback on:
- My script.js
- My layout
- My pseudo
- My style

**Comment by mattscilipoti** [comment]
:+1: Good job on Project 1!
I've completed your feedback.  Please review feedback_mms.md and the inline comments here:
https://github.com/mkernsNCR/project-war/pull/1
