### ISSUE TITLE
Maureen's Project

### ISSUE THREAD

**Issue by maureenv** [ga-dc/wdi8-project1-gallery#34]
Link to repo: http://maureenv.github.io/project1/
Link to deployed app:

Things you'd like specific feedback on: Need help on line 67 in my javacript file. I'm trying to add a count down to my project in my h2 tag in HTML. However the following code won't change the number in my HTML tag according to the number of clicks:

``` javascript

document.getElementsByClassName('counter').innerHTML='HELLO';
```

**Comment by mattscilipoti** [comment]
:+1: Good job on Project 1!
I've completed your feedback.  Please review feedback_mms.md and the inline comments here:
https://github.com/mattscilipoti/wdi8_project1_mv/compare/feedback_mms
