### ISSUE TITLE
Chinese Flash Cards

### ISSUE THREAD

**Issue by MaxKaye** [ga-dc/wdi8-project1-gallery#35]
Link to repo: git@github.com:MaxKaye/flashcardproject1.git
Link to deployed app: http://maxkaye.github.io/flashcardproject1/flashcard.html

Things you'd like specific feedback on:
Less reuse of code

**Comment by mattscilipoti** [comment]
:+1: Good job on Project 1!
I've completed your feedback.  Please review feedback_mms.md and the inline comments here: https://github.com/MaxKaye/flashcardproject1/pull/1
