### ISSUE TITLE
My Project-1 (Kaira Johnson)

### ISSUE THREAD

**Issue by kairajohnson** [ga-dc/wdi8-project1-gallery#38]
Link to repo: kairajohnson/project1
Link to deployed app: http://kairajohnson.github.io/project1/ 

Things you'd like specific feedback on:

In my code, there is a portion that is duplicate and when I delete the duplicate, it doesn't work.... not sure why. This is the part:

```
//score


function yesButton (){
    console.log(this)
  if(this === yes){
    points = points + 1;
  document.getElementById('score').innerHTML = "SCORE: " + points;
}
}
function yesButton (){
    console.log(this)
  if(this === yes){
    points = points + 1;
  document.getElementById('score').innerHTML = "SCORE: " + points;
}
if (points === 5)
{
   points = 0;
}
}
yes.addEventListener('click', yesButton)

document.getElementById('score').innerHTML = "SCORE: " + points;


```

**Comment by joe-gz** [comment]
Hi Kaira,

Please see the below links for in line comments as well as the overall feedback rubric. Take a look at my notes, and let me know if you'd like to sit down and go through some of them. I think this is a good start, but there is a lot we can do to improve this quickly!

The link to the feedback is here (note, there are a couple inline comments here as well): https://github.com/joe-gz/kairaJohnson---project1/commit/cdafb8ecc5c4654c0a7bfeafc0f5e990487b327e

The link to the in line comments (note, i addressed your question above in the comments in line): https://github.com/joe-gz/kairaJohnson---project1/commit/bdd0db18b63e161f0670734a84a1578878d4034c

Please let me know if you have any questions!
