### ISSUE TITLE
Casey_Solution_Bronze

### ISSUE THREAD

**Issue by caseyagil** [ga-dc/wdi8-project1-gallery#5]
Link to repo: https://github.com/caseyagil/russianwargame
Link to deployed app: http://caseyagil.github.io/russianwargame/

Things you'd like specific feedback on:
variations on how I can improve the way I code.  I confused myself a few times with inline coding errors.  And after talking with other people, I noticed some placed a lot in JS files while some had everything spread out.  Or is it mainly a personality of the developer while coding.

**Comment by beckybeauchamp1** [comment]
Hi Casey,

Great job on Project 1! I just made a PR to your repo that includes the evaluation template as well as inline comments on your code:

Link to PR: https://github.com/caseyagil/russianwargame/pull/1/files
Link to Evaluation: https://github.com/beckybeauchamp1/russianwargame/blob/beckys-branch/evaluation-template.md

Please let me know if you have any further questions :+1:
